name: Changelog

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run conventional commits
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
